In [2]:
import numpy as np
from scipy.sparse import csr_matrix
from scipy.spatial.distance import cdist, pdist, squareform

data = np.array([1, 2, 3, 4])
row = np.array([0, 0, 1, 2])
col = np.array([0, 2, 2, 0])
sparse_matrix = csr_matrix((data, (row, col)), shape=(3, 3))

print("稀疏矩阵:")
print(sparse_matrix.toarray())

dense_matrix = sparse_matrix.toarray()
euclidean_dist = squareform(pdist(dense_matrix, 'euclidean'))

print("\n欧几里得距离矩阵:")
print(euclidean_dist)

cosine_dist = squareform(pdist(dense_matrix, 'cosine'))

print("\n余弦距离矩阵:")
print(cosine_dist)

稀疏矩阵:
[[1 0 2]
 [0 0 3]
 [4 0 0]]

欧几里得距离矩阵:
[[0.         1.41421356 3.60555128]
 [1.41421356 0.         5.        ]
 [3.60555128 5.         0.        ]]

余弦距离矩阵:
[[0.         0.10557281 0.5527864 ]
 [0.10557281 0.         1.        ]
 [0.5527864  1.         0.        ]]
